### ISSUE TITLE
Falling in space unable to play

### ISSUE THREAD

**Issue by NyxKhaos** [Pingu-Pox/duncraft-reborn#21]
I killed a beast that spawned mobs after its death (the hissing mice looking bugs that come out of dungeon stone) which then killed me. I spawned back in at my bed. Went to try to retrieve my grave. Key did not appear right away, guessing lag. I was standing at grave trying to access it but nothing worked probably due to being in the process of being disconnected which happened a few seconds after. I tried to reconnect and I fell through space and disconnected again. I closed down the server join page, and MultiMC 5 completely. Reopened it to try again, in hopes fully closing and reopening might fix issue. Sadly same issue. I Spawn in only able to see the sky with the sun then just black abyss below and I continue to fall forever. This time it actually gave me a crash log the 3rd time)

Hoping I did this right
https://paste.ee/p/tbSXa

**Comment by Pingu-Pox** [comment]
Pasting bits of your log here for my reference:

```
Thread: Render thread
Stacktrace:
	at smartin.tetraticcombat.ItemResolver.Resolver.findWeaponByNBT(Resolver.java:50) ~[tetratic-combat-2.1.jar%23237!/:2.1] {re:mixin,re:classloading}
	at smartin.tetraticcombat.ItemResolver.Resolver.generateBetterCombatNBT(Resolver.java:68) ~[tetratic-combat-2.1.jar%23237!/:2.1] {re:mixin,re:classloading}
	at smartin.tetraticcombat.ItemResolver.Resolver.generateBetterCombatNBT(Resolver.java:61) ~[tetratic-combat-2.1.jar%23237!/:2.1] {re:mixin,re:classloading}
```

```
-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.client.player.LocalPlayer)
	Entity ID: 1758914
	Entity Name: NyxKhaos24
	Entity's Exact location: 333.30, -1607.81, 418.57
	Entity's Block location: World: (333,-1608,418), Section: (at 13,8,2 in 20,-101,26; chunk contains blocks 320,-64,416 to 335,319,431), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -3.92, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at dev.wuffs.itshallnottick.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:59) ~[ItShallNotTick-1.0.22-build.34.jar%23163!/:1.0.22-build.34] {re:mixin,re:classloading}
	at dev.wuffs.itshallnottick.TickOptimizer.entityTicking(TickOptimizer.java:22) ~[ItShallNotTick-1.0.22-build.34.jar%23163!/:1.0.22-build.34] {re:mixin,re:classloading}

```
